name: "Argocd Sync Application Action"
description: "This action has the objective of simplify sync application in the argocd."
inputs:
  environment:
    description: "Environment to run the action."
    required: true
  argocd-host:
    description: 'ArgoCD access endpoint.'
    required: true
  argocd-user:
    description: 'ArgoCD access user.'
    required: true
  argocd-password:
    description: 'ArgoCD access password.'
    required: true
  argocd-application:
    description: 'Application to sync in the ArgoCD.'
    required: true
runs:
  using: "node20"
  main: "index.js"
